version: '3.8'

services:
 proxy:
    image: haproxytech/haproxy-alpine:2.7
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8404:8404"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
