version: "3.8"

services:
  proxy:
    image: haproxytech/haproxy-alpine:2.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8404:8404"
    env_file:
      - ./.env.local
    volumes:
      - ./haproxy-prod.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /etc/letsencrypt/live/oxfamsurvivorscommunity.uksouth.cloudapp.azure.com/haproxy.pem:/tls/haproxy.pem:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
