version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    command: --noscripting
    volumes:
      - ./docker-volumes/mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
