version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 127.0.0.1:5672:5672

  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_USERNAME: USER
      MONGO_PASSWORD: PASS
      MONGO_INITDB_DATABASE: trendsdata
    command: --noscripting
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  api:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: root
      MONGO_USERNAME: USER
      MONGO_PASSWORD: PASS
      DATABASE_NAME: trendsdata
      DATABASE_URL: mongo
      DATABASE_PORT: 27017
      PORT: 3000
    ports:
      - 127.0.0.1:${E2E_DB_PORT}:27017
