version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_USERNAME: USER
      MONGO_PASSWORD: PASS
      MONGO_INITDB_DATABASE: reportdata
    command: --noscripting
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - ${E2E_DB_PORT}:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    build: .
    depends_on:
      - mongo
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: root
      MONGO_USERNAME: USER
      MONGO_PASSWORD: PASS
      DATABASE_NAME: reportdata
      MONGO_URL: mongodb://USER:PASS@mongo:27017/reportdata
      PORT: 3000
      RABBITMQ_HOSTNAME: localhost

