version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    command: --noscripting
    volumes:
      - ./docker-volumes/mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  api:
    depends_on:
      - mongo
    image: ghcr.io/adnanben/oxfam-0102/resources:main
    env_file: ./.env
    ports:
      - 127.0.0.1:${PROXY_PORT}:${PORT}
