version: '3.8'

services:
  api:
    image: ghcr.io/adnanben/oxfam-0102/forum:main
    depends_on:
      - postgres
    restart: unless-stopped
    env_file: .env.local

  postgres:
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
