version: '3.8'

services:
  api:
    build: .
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: forum
      POSTGRES_PASSWORD: forum
      DATABASE_NAME: forum
      DATABASE_URL: "postgresql://forum:forum@postgres:5432/forum"
      PORT: 3000

  postgres:
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: forum
      POSTGRES_PASSWORD: forum
