version: '3.8'

services:
  api:
    build: .
    restart: unless-stopped
    ports: 127.0.0.1:8000:${PORT}

  postgres:
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /docker-volumes/postgres:/var/lib/postgresql/data
      # - /etc/passwd:/etc/passwd:ro
