version: '3.8'

services:
  api:
    build: .
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:${PROXY_PORT}:${PORT}

  postgres:
    image: 'postgres:15-alpine'
    restart: unless-stopped
    # ports:
    #   - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
      # - /etc/passwd:/etc/passwd:ro
