version: '3.8'

services:
  api:
    build: .
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: USER
      POSTGRES_PASSWORD: PASS
      DATABASE_NAME: forum
      DATABASE_URL: "postgresql://USER:PASS@postgres:5432/forum"
      PORT: 3000
      NODE_ENV: test

  postgres:
    image: 'postgres:15-alpine'
    restart: unless-stopped
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASS
    ports:
      - ${E2E_DB_PORT}:5432
